package groth16

// solanaTemplate contains a Rust verifier for Solana using arkworks. It embeds
// the verifying key generated by gnark and can optionally embed a test vector
// to exercise the verifier off-chain.
const solanaTemplate = `// Code generated by gnark DO NOT EDIT.
#![allow(non_snake_case)]

//! Solana verifier for Groth16 BN254 proofs generated by gnark.
//! Exposes verify plus the embedded verifying key and optional test vector.

// Program name: {{ .Cfg.ProgramName }}
use ark_bn254::{Bn254, Fq, Fq2, Fr, G1Affine, G2Affine};
use ark_groth16::{prepare_verifying_key, Groth16, Proof, VerifyingKey};
use std::str::FromStr;

pub const NB_PUBLIC_INPUTS: usize = {{ sub (len .Vk.G1.K) 1 }};
pub const PROGRAM_NAME: &str = "{{ .Cfg.ProgramName }}";

fn fq(v: &str) -> Fq {
    Fq::from_str(v).expect("invalid Fq literal")
}

fn fq2(a0: &str, a1: &str) -> Fq2 {
    Fq2::new(fq(a0), fq(a1))
}

fn fr(v: &str) -> Fr {
    Fr::from_str(v).expect("invalid Fr literal")
}

fn g1(x: &str, y: &str) -> G1Affine {
    G1Affine::new_unchecked(fq(x), fq(y))
}

fn g2(x0: &str, x1: &str, y0: &str, y1: &str) -> G2Affine {
    G2Affine::new_unchecked(fq2(x0, x1), fq2(y0, y1))
}

pub fn verifying_key() -> VerifyingKey<Bn254> {
    VerifyingKey {
        alpha_g1: g1("{{ (fpstr .Vk.G1.Alpha.X) }}", "{{ (fpstr .Vk.G1.Alpha.Y) }}"),
        beta_g2: g2(
            "{{ (fpstr .Vk.G2.Beta.X.A0) }}",
            "{{ (fpstr .Vk.G2.Beta.X.A1) }}",
            "{{ (fpstr .Vk.G2.Beta.Y.A0) }}",
            "{{ (fpstr .Vk.G2.Beta.Y.A1) }}",
        ),
        gamma_g2: g2(
            "{{ (fpstr .Vk.G2.Gamma.X.A0) }}",
            "{{ (fpstr .Vk.G2.Gamma.X.A1) }}",
            "{{ (fpstr .Vk.G2.Gamma.Y.A0) }}",
            "{{ (fpstr .Vk.G2.Gamma.Y.A1) }}",
        ),
        delta_g2: g2(
            "{{ (fpstr .Vk.G2.Delta.X.A0) }}",
            "{{ (fpstr .Vk.G2.Delta.X.A1) }}",
            "{{ (fpstr .Vk.G2.Delta.Y.A0) }}",
            "{{ (fpstr .Vk.G2.Delta.Y.A1) }}",
        ),
        gamma_abc_g1: vec![
            {{- range $i, $k := .Vk.G1.K }}
            g1("{{ (fpstr $k.X) }}", "{{ (fpstr $k.Y) }}"),
            {{- end }}
        ],
    }
}

pub fn verify(public_inputs: &[Fr], proof: &Proof<Bn254>) -> bool {
    let pvk = prepare_verifying_key(&verifying_key());
    Groth16::<Bn254>::verify_proof(&pvk, proof, public_inputs).unwrap_or(false)
}

pub fn g1_from_strs(x: &str, y: &str) -> G1Affine {
    g1(x, y)
}

pub fn g2_from_strs(x0: &str, x1: &str, y0: &str, y1: &str) -> G2Affine {
    g2(x0, x1, y0, y1)
}

{{- if .Cfg.TestVector }}
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verifies_sample_proof() {
        let proof = Proof::<Bn254> {
            a: g1_from_strs("{{ index .Cfg.TestVector.Proof.A 0 }}", "{{ index .Cfg.TestVector.Proof.A 1 }}"),
            b: g2_from_strs(
                "{{ index (index .Cfg.TestVector.Proof.B 0) 0 }}",
                "{{ index (index .Cfg.TestVector.Proof.B 0) 1 }}",
                "{{ index (index .Cfg.TestVector.Proof.B 1) 0 }}",
                "{{ index (index .Cfg.TestVector.Proof.B 1) 1 }}",
            ),
            c: g1_from_strs("{{ index .Cfg.TestVector.Proof.C 0 }}", "{{ index .Cfg.TestVector.Proof.C 1 }}"),
        };

        let public_inputs: Vec<Fr> = vec![
            {{- range $i, $pi := .Cfg.TestVector.PublicInputs }}
            fr("{{ $pi }}"),
            {{- end }}
        ];

        assert!(verify(&public_inputs, &proof));
    }
}
{{- end }}
`
